FROM python:3.12-slim-bookworm as stage1

RUN echo "I'm stage 1"

WORKDIR /opt/sample-app

COPY ./sample-app /opt/sample-app



FROM python:3.12-slim-bookworm as stage2

RUN echo "I'm stage 2"

WORKDIR /opt/sample-app

COPY --from=stage1 /opt/sample-app /opt/sample-app

RUN pip install /opt/sample-app

EXPOSE 5000

CMD ["python", "/opt/sample-app/app/main.py"]
